In [13]:
import numpy as np
var1 = np.array(([2,4,6],[1,3,5]))

In [10]:
var2= np.array(([5,9,3],[6,7,15]))

In [14]:
var1/var2

array([[0.4       , 0.44444444, 2.        ],
       [0.16666667, 0.42857143, 0.33333333]])

In [15]:
var1.ravel()

array([2, 4, 6, 1, 3, 5])

In [16]:
var1.sum()

21

In [17]:
np.sqrt(var1)

array([[1.41421356, 2.        , 2.44948974],
       [1.        , 1.73205081, 2.23606798]])

In [18]:
np.std(var1)

1.707825127659933

In [19]:
np.std(var2)

3.8188130791298667

In [22]:
var1

array([[2, 4, 6],
       [1, 3, 5]])

In [21]:
np.exp(var1)

array([[  7.3890561 ,  54.59815003, 403.42879349],
       [  2.71828183,  20.08553692, 148.4131591 ]])

In [23]:
np.exp(var2)

array([[1.48413159e+02, 8.10308393e+03, 2.00855369e+01],
       [4.03428793e+02, 1.09663316e+03, 3.26901737e+06]])

In [24]:
var3 = np.array([3,6,9])

In [25]:
np.exp(var3)

array([  20.08553692,  403.42879349, 8103.08392758])

In [26]:
np.log(var1)

array([[0.69314718, 1.38629436, 1.79175947],
       [0.        , 1.09861229, 1.60943791]])

In [27]:
np.log(var3)

array([1.09861229, 1.79175947, 2.19722458])

In [28]:
var1

array([[2, 4, 6],
       [1, 3, 5]])

In [30]:
var3

array([3, 6, 9])

In [31]:
np.exp(var3)

array([  20.08553692,  403.42879349, 8103.08392758])