In [1]:
import pandas as pd
import numpy as np

In [6]:
df= pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv')

<IPython.core.display.Javascript object>

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      6 non-null      int32
 1   bedrooms  6 non-null      int32
 2   age       6 non-null      int32
 3   price     6 non-null      int32
dtypes: int32(4)
memory usage: 224.0 bytes


In [6]:
a.to_csv('homeprices.csv')

In [7]:
from sklearn import linear_model

In [11]:
import math
median_bedrooms =math.floor(df.bedrooms.median())

In [12]:
median_bedrooms

4

In [17]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      6 non-null      int32
 1   bedrooms  6 non-null      int32
 2   age       6 non-null      int32
 3   price     6 non-null      int32
dtypes: int32(4)
memory usage: 224.0 bytes


In [38]:
a = np.array([2600,3000,3200,3600,4000,4100])

In [41]:
b=np.array([3,4,4,3,5,6])
c=np.array([20,15,18,30,8,8])
d=np.array([550000,565000,610000,595000,760000,80000])

In [42]:
df= pd.DataFrame({'area':a,'bedrooms':b,'age':c,'price':d})

In [4]:
df

NameError: name 'df' is not defined

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   area      6 non-null      int32
 1   bedrooms  6 non-null      int32
 2   age       6 non-null      int32
 3   price     6 non-null      int32
dtypes: int32(4)
memory usage: 224.0 bytes


In [52]:
df= df.astype('int')

In [56]:
pd.to_numeric(df.area)

0    2600
1    3000
2    3200
3    3600
4    4000
5    4100
Name: area, dtype: int32

In [ ]:
pd.to_numeri 

In [53]:
reg= linear_model.LinearRegression()

In [57]:
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [59]:
reg.coef_

array([ 4.71794639e+02, -6.22342819e+05, -5.36989752e+04])

In [60]:
reg.intercept_


2393829.8177643847

In [61]:
reg.predict([[3000,3,40]])

array([-205773.72725831])

In [63]:
import pandas as pd

In [7]:
df= pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/5_one_hot_encoding/homeprices.csv')

<IPython.core.display.Javascript object>

In [69]:
pd.get_dummies(df.town)

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [70]:
dummies = pd.get_dummies(df.town)

In [80]:
merged = pd.concat([df,dummies],axis= 'columns')

In [81]:
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [82]:
final=merged.drop(['town','west windsor'],axis='columns')

In [83]:
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [84]:
from sklearn import linear_model

In [85]:
reg= linear_model.LinearRegression()

In [88]:
reg.fit(final[['area','monroe township','robinsville']],final.price)

LinearRegression()

In [89]:
reg.predict([[2800,0,1]])

array([590775.63964739])

In [90]:
reg.score(final[['area','monroe township','robinsville']],final.price)

0.9573929037221873

In [1]:
from sklearn import preprocessing

In [2]:
le= preprocessing.LabelEncoder()

In [8]:
dfle= df

In [9]:
dfle.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [11]:
dfle.town = le.fit_transform(dfle.town)

In [14]:
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [15]:
from sklearn import linear_model

In [16]:
reg= linear_model.LinearRegression()

In [46]:
X= dfle[['town','area']].values

In [53]:
X

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [47]:
y = dfle.price

In [48]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
ohe = OneHotEncoder()

In [50]:
X= ohe.fit_transform(X).toarray()
X

array([[1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [51]:
X= X[:,1:]

In [52]:
X

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [54]:
from sklearn.linear_model import LinearRegression

In [55]:
model = LinearRegression()

In [56]:
model.fit(X,y)

LinearRegression()

In [57]:
model.predict([[1,0,2800]])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 11 is different from 3)